### ISSUE TITLE
Input-Clock error on first load

### ISSUE THREAD

**Issue by breferrari** [krescruz/angular-materialize#165]
Whenever I load a view that contains a clock picker I get this error

`Error: element.clockpicker is not a function. (In 'element.clockpicker', 'element.clockpicker' is undefined)
link@http://localhost:8888/bower_components/angular-materialize/src/angular-materialize.js:737:44
http://localhost:8888/bower_components/angular/angular.js:9083:49
invokeLinkFn@http://localhost:8888/bower_components/angular/angular.js:9089:15
nodeLinkFn@http://localhost:8888/bower_components/angular/angular.js:8576:23
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7975:23
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7978:24
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7978:24
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7978:24
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7978:24
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7978:24
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7978:24
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7978:24
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7978:24
nodeLinkFn@http://localhost:8888/bower_components/angular/angular.js:8571:35
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7975:23
publicLinkFn@http://localhost:8888/bower_components/angular/angular.js:7855:45
http://localhost:8888/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:23888
invokeLinkFn@http://localhost:8888/bower_components/angular/angular.js:9089:15
nodeLinkFn@http://localhost:8888/bower_components/angular/angular.js:8576:23
compositeLinkFn@http://localhost:8888/bower_components/angular/angular.js:7975:23
publicLinkFn@http://localhost:8888/bower_components/angular/angular.js:7855:45
k@http://localhost:8888/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:23133
http://localhost:8888/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:23402
$broadcast@http://localhost:8888/bower_components/angular/angular.js:16697:33
http://localhost:8888/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:18779
processQueue@http://localhost:8888/bower_components/angular/angular.js:15112:30
http://localhost:8888/bower_components/angular/angular.js:15128:39
$eval@http://localhost:8888/bower_components/angular/angular.js:16374:28
$digest@http://localhost:8888/bower_components/angular/angular.js:16190:36
$apply@http://localhost:8888/bower_components/angular/angular.js:16482:31
done@http://localhost:8888/bower_components/angular/angular.js:10862:53
completeRequest@http://localhost:8888/bower_components/angular/angular.js:11060:15
requestLoaded@http://localhost:8888/bower_components/angular/angular.js:11001:24 – "<input id=\"input_starttime\" input-clock=\"\" data-twelvehour=\"false\" data-autoclose=\"true\" data-darktheme=\"true\" data-donetext=\"Pronto…"`

If I reload the page, the error goes away and the picker works just fine.

**Comment by webbiesdk** [comment]
I think you forgot to materialize-clockpicker JavaScript file 
https://github.com/chingyawhao/materialize-clockpicker

If that wasn't the case, then I don't know what caused it. 

Could you provide a link to a page where the issue is present, otherwise i cannot help you any further.

**Comment by aitchkhan** [comment]
I have the same issue as well 
My index.html containing scripts is like

> materiz/js/materialize.js
> materialize-clockpicker.js
> angular-materialize.js
> 
> ```
> TypeError: t.clockpicker is not a function
>     at link (http://localhost/delivery-chacha/back-office/node_modules/angular-materialize/src/angular-materialize.min.js:1:11168)
>     at http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:8275:44
>     at invokeLinkFn (http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:8281:9)
>     at nodeLinkFn (http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:7791:11)
>     at compositeLinkFn (http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:7140:13)
>     at nodeLinkFn (http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:7786:24)
>     at compositeLinkFn (http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:7140:13)
>     at compositeLinkFn (http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:7143:13)
>     at compositeLinkFn (http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:7143:13)
>     at compositeLinkFn (http://localhost/delivery-chacha/back-office/shared/bower_components/angular/angular.js:7143:13) <input id="input_starttime" input-clock="" data-twelvehour="false" type="text" style=" padding-left: 38px; top: 1px; width: 75%;" class="ng-isolate-scope timepicker">
> ```

**Comment by webbiesdk** [comment]
In that case, provide a link to a page that has the problem.

Otherwise I have no way to precisely identify what the actual problem is.
